name: pokedex_egsys
description: A Flutter Pokedex.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  lottie: ^2.2.0
  shimmer: ^3.0.0
  get_it: ^7.6.0
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.5
  http_mock_adapter: ^0.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins_Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins_Bold.ttf
          weight: 700

    - family: Pokemon
      fonts:
        - asset: assets/fonts/pokemon/Pokemon_Hollow.ttf
          weight: 400
        - asset: assets/fonts/pokemon/Pokemon_Solid.ttf
          weight: 700
